http:
  routers:
    platform:
      rule: "Host(`vuhom.com`) || Host(`www.vuhom.com`)"
      entryPoints:
        - https
      tls:
        certResolver: letsencrypt
      service: platform

    api:
      rule: "Host(`api.vuhom.com`)"
      entryPoints:
        - https
      tls:
        certResolver: letsencrypt
      service: api

    admin:
      rule: "Host(`admin.vuhom.com`)"
      entryPoints:
        - https
      tls:
        certResolver: letsencrypt
      service: admin

  services:
    platform:
      loadBalancer:
        servers:
          - url: "http://vuhom-platform:3000"

    api:
      loadBalancer:
        servers:
          - url: "http://vuhom-api:8003"

    admin:
      loadBalancer:
        servers:
          - url: "http://vuhom-admin:80"
